### ISSUE TITLE
Not fully compatible with sprintdoc template

### ISSUE THREAD

**Issue by fwolfst** [zioth/dokuwiki_fastwiki#34]
As described in https://github.com/cosmocode/dokuwiki-template-sprintdoc/issues/23 it seems that fastwiki somehow deals with the message area in a way that leads to suboptimal rendering when the SprintDoc template is used.
I am not sure which project can achieve an easy improvement, so i leave these two issues open for the respective maintainers ... :) thanks for all your cool work.

**Comment by mr-floppy** [comment]
I can confirm that.
The text above the edit box moves under the message area, if one edits the whole page.

Strangely I never noticed that until right now, so it is not a game braking bug, beacuse nobody reads the instructions above the box anyways ;)

**Comment by mr-floppy** [comment]
The problem is, that fastwiki introduces a new css class `content_partial`.

Without fastwiki: 
![without_fastwiki](https://user-images.githubusercontent.com/8448697/59807700-501b7700-92f9-11e9-95b7-1f11495438b5.png)

With fastwiki:
![with_fastwiki](https://user-images.githubusercontent.com/8448697/59807629-0b8fdb80-92f9-11e9-9091-03317457f734.png)

```css
/* file: fastwiki/screen.css: */
.content_partial {
        clear: both;
}
```

I have played around with it just a little bit, but the only quick&dirty fix I came up with so far was to just hide the message area completely while editing the page:
```css
/* file: fastwiki/screen.css: */
.content_partial.page.main-content::before {
        display: none;
}
```

This is just a proof of concept. There has to be a way more elegant approach to this.
